# Generated by Django 6.0.1 on 2026-02-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='api_key',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
    ]
