# Generated by Django 6.0.1 on 2026-02-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_maquina_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esp32Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('storage', 'Storage'), ('error', 'Error')], default='offline', max_length=20)),
                ('memoria_ocupada', models.IntegerField(default=0, help_text='En bytes')),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('intervalo_actual', models.IntegerField(default=900, help_text='Intervalo de lectura en segundos')),
                ('batch_pendientes', models.IntegerField(default=0, help_text='Número de batches sin enviar (reportado por ESP32)')),
                ('ultimo_reinicio', models.DateTimeField(blank=True, null=True)),
                ('alertas', models.JSONField(blank=True, default=dict)),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esp32_estado', to='api.maquina')),
            ],
            options={
                'verbose_name': 'Estado ESP32',
                'verbose_name_plural': 'Estados ESP32',
                'db_table': 'esp32_estados',
            },
        ),
    ]
