# Generated by Django 6.0.1 on 2026-03-01 04:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_esp32estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField()),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('esp32', 'ESP32'), ('app', 'App')], default='manual', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.inventariomaquina')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='api.maquina')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.visita')),
            ],
            options={
                'verbose_name': 'Recarga',
                'verbose_name_plural': 'Recargas',
                'db_table': 'recargas',
                'ordering': ['-fecha'],
            },
        ),
    ]
