# Generated by Django 6.0.1 on 2026-03-03 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recarga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recarga',
            name='responsable',
        ),
        migrations.AddField(
            model_name='recarga',
            name='conteo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas', to='api.conteo'),
        ),
        migrations.AddField(
            model_name='recarga',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recarga',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de compra del producto', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recarga',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio al que se venderá', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recarga',
            name='inventario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='api.inventariomaquina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recarga',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('esp32', 'Automática por ESP32'), ('programada', 'Programada')], default='esp32', max_length=20),
        ),
        migrations.AlterField(
            model_name='recarga',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='api.producto'),
        ),
        migrations.AlterField(
            model_name='recarga',
            name='visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas', to='api.visita'),
        ),
    ]
