# Generated by Django 6.0.1 on 2026-03-26 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_recarga_responsable_recarga_conteo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esp32Slave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(help_text='Identificador de la bandeja (A, B, C, ...)', max_length=10)),
                ('codigo_producto', models.CharField(blank=True, help_text='Código del producto en esta bandeja (opcional)', max_length=50, null=True)),
                ('firmware_version', models.CharField(default='v1.0', max_length=20)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('online', 'En línea'), ('offline', 'Desconectada'), ('reading', 'Leyendo sensores'), ('error', 'Error'), ('calibrating', 'Calibrando')], default='offline', max_length=20)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('distancia_min', models.FloatField(default=0, help_text='Distancia mínima en mm para considerar producto presente')),
                ('distancia_max', models.FloatField(default=200, help_text='Distancia máxima en mm')),
                ('posiciones', models.JSONField(blank=True, default=list, help_text='Lista de códigos de espiral en orden físico')),
                ('ultima_lectura', models.JSONField(blank=True, default=dict, help_text='Última lectura recibida: {posicion: cantidad, ...}')),
                ('ultima_lectura_fecha', models.DateTimeField(blank=True, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slaves', to='api.maquina')),
            ],
            options={
                'unique_together': {('maquina', 'posicion')},
            },
        ),
        migrations.CreateModel(
            name='Esp32Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Advertencia'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('mensaje', models.TextField()),
                ('datos_extra', models.JSONField(blank=True, default=dict, help_text='Información adicional (ej. batch_id, errores específicos)')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.maquina')),
                ('slave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.esp32slave')),
            ],
        ),
        migrations.CreateModel(
            name='Esp32Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(choices=[('leer_todo', 'Leer todas las bandejas'), ('leer_bandeja', 'Leer una bandeja específica'), ('leer_posicion', 'Leer una posición específica en una bandeja'), ('calibrar', 'Calibrar una bandeja'), ('test', 'Ejecutar prueba de hardware'), ('reiniciar', 'Reiniciar esclava'), ('actualizar_firmware', 'Actualizar firmware (avanzado)')], max_length=50)),
                ('parametros', models.JSONField(blank=True, default=dict, help_text='Parámetros adicionales del comando (ej. posicion, batch_id)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ejecutado', models.BooleanField(default=False)),
                ('ejecutado_en', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.JSONField(blank=True, default=dict, help_text='Respuesta del comando (si aplica)')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='api.maquina')),
                ('slave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandos', to='api.esp32slave')),
            ],
        ),
    ]
