name: inventory_app
description: Sistema de Inventario para Máquinas Dispensadoras
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  fl_chart: ^0.64.0
  flutter_local_notifications: ^15.0.0
  timezone: ^0.9.4
  url_launcher: ^6.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env